languageCode = 'en-us'
baseURL = 'https://example.org/'
title = 'Muqeeth blog'

paginate = 4

[params]
  description = "The fastest blog"
  dateFormat = "Jan 2 , 2006"

[taxonomies]
  category = "categories"
  author  = "authors"